
include: "rules/common.smk"
include: "rules/fastp.smk"
include: "rules/fastqc.smk"
include: "rules/salmon_quant.smk"
include: "rules/multiqc.smk"


rule all:
    input:
        "results/multiqc.html",
