rule multiqc:
    input:
        "results/busco/short_summary.txt",
        "results/seqkit/fx2tab_mqc.txt",
        "results/seqkit/stats_mqc.txt",
        expand(
            "results/fastp/{sample}_fastp.json",
            sample=sample_data.index.tolist(),
        ), 
        expand(
           "results/fastqc/{sample}_R1.html",
           sample=sample_data.index.tolist(),
        ),
        expand(
            "results/fastqc/{sample}_R2.html",
            sample=sample_data.index.tolist(),
        ),
        expand(
            "results/salmon/{group}/aux_info/meta_info.json",
            group=dict_groups.keys(),
        ),
        config="config/config_multiqc.yaml",
    output:
        "results/multiqc.html",
        directory("results/multiqc_data"),
    params:
        extra="--verbose",  # Optional: extra parameters for multiqc.
    log:
        "logs/multiqc.log",
    wrapper:
        "v7.5.0/bio/multiqc"
