
# path to sample sheet csv with columns for ID,forward,reverse
samples: sample_list_Ecry.csv

# path to reference fasta file for alignment
reference: /mnt/shared/projects/nhm/owhite/krill_transcriptome_assembly_Ecry/results/trinity/trinity_Ecry.Trinity.fasta

# path to salmon index
salmon_index: "/mnt/shared/projects/nhm/owhite/krill_transcriptome_assembly_Ecry/results/salmon_index/"