
# path to sample sheet csv with columns for ID,forward,reverse
samples:  sample_list_Esup.csv

# path to reference fasta file for alignment
reference: /home/owhite/scratch/private/krill_transcriptome_assembly_Esup/results/trinity/trinity_Esup.Trinity.fasta

# path to salmon index
salmon_index: "/home/owhite/scratch/private/krill_transcriptome_assembly_Esup/results/salmon_index/"
